'use strict';

/**
 * Offline HMAC-SHA256 license system.
 *
 * Key format: AAAAAA-BBBBBB-CCCCCC-DDDDDD (24 hex chars, no prefix)
 *   - Groups 1-3 (18 hex = 9 bytes): first 9 bytes of HMAC-SHA256(payload, SECRET)
 *   - Group  4   ( 6 hex = 3 bytes): payload  [tier(1 byte) + expiryDays(2 bytes BE)]
 *
 * tier values: 0x01 = standard, 0x02 = pro, 0xFF = lifetime
 * expiryDays : uint16 BE, days since Unix epoch (0xFFFF = lifetime)
 *
 * Generated by scripts/keygen.js (developer-only tool).
 */

const crypto = require('crypto');
const fs     = require('fs');
const path   = require('path');

// ─── Private key baked into the binary ───────────────────────────────────────
// Change this before every major version release; keep it secret.
const SECRET = 'SAS-Garments-License-V1-2024-xK9mP2qW';

const LICENSE_FILE   = 'license.key';
const TRIAL_FILE     = 'trial-start.dat';
const TRIAL_DAYS     = 30;

const TIER_MAP  = { 0x01: 'standard', 0x02: 'pro', 0xff: 'lifetime' };
const TIER_RMAP = { standard: 0x01, pro: 0x02, lifetime: 0xff };

// ─── Core crypto ─────────────────────────────────────────────────────────────

function hmac9(payloadBuf) {
  return crypto.createHmac('sha256', SECRET).update(payloadBuf).digest();
}

// ─── Key encode/decode ────────────────────────────────────────────────────────

/**
 * Build a license key from tier + expiry date.
 * @param {'standard'|'pro'|'lifetime'} tier
 * @param {Date} expiryDate  — ignored when tier === 'lifetime'
 */
function buildKey(tier, expiryDate) {
  const tierByte = TIER_RMAP[tier] ?? 0x01;
  const days     = tierByte === 0xff
    ? 0xffff
    : Math.floor(expiryDate.getTime() / 86400000);

  const payload = Buffer.alloc(3);
  payload.writeUInt8(tierByte, 0);
  payload.writeUInt16BE(Math.min(days, 0xffff), 1);

  const sig     = hmac9(payload);               // 32-byte HMAC
  const raw     = Buffer.concat([sig.slice(0, 9), payload]); // 12 bytes = 24 hex

  const hex = raw.toString('hex').toUpperCase();
  return `${hex.slice(0,6)}-${hex.slice(6,12)}-${hex.slice(12,18)}-${hex.slice(18,24)}`;
}

/**
 * Validate a key string. Returns status object or null on bad format.
 */
function validateKey(keyString) {
  if (!keyString || typeof keyString !== 'string') {
    return { valid: false, error: 'No key provided.' };
  }

  const hex = keyString.replace(/-/g, '').toUpperCase();
  if (!/^[0-9A-F]{24}$/.test(hex)) {
    return { valid: false, error: 'Invalid key format.' };
  }

  const raw     = Buffer.from(hex, 'hex');        // 12 bytes
  const sigPart = raw.slice(0, 9);               // first 9 bytes
  const payload = raw.slice(9, 12);              // last  3 bytes

  // Verify HMAC
  const expectedSig = hmac9(payload).slice(0, 9);
  if (!crypto.timingSafeEqual(sigPart, expectedSig)) {
    return { valid: false, error: 'Invalid license key.' };
  }

  const tierByte   = payload.readUInt8(0);
  const expiryDays = payload.readUInt16BE(1);
  const tier       = TIER_MAP[tierByte] ?? 'standard';
  const isLifetime = tierByte === 0xff || expiryDays === 0xffff;

  const expiryDate = isLifetime
    ? new Date(2099, 11, 31)
    : new Date(expiryDays * 86400000);

  const now      = new Date();
  const daysLeft = isLifetime
    ? Infinity
    : Math.ceil((expiryDate.getTime() - now.getTime()) / 86400000);

  const expired = !isLifetime && daysLeft <= 0;

  return {
    valid:      !expired,
    tier,
    isLifetime,
    expiryDate: expiryDate.toISOString().slice(0, 10),
    daysLeft:   isLifetime ? null : daysLeft,
    expired,
  };
}

// ─── Persistence ──────────────────────────────────────────────────────────────

function licensePath(userDataPath) {
  return path.join(userDataPath, LICENSE_FILE);
}

function trialPath(userDataPath) {
  return path.join(userDataPath, TRIAL_FILE);
}

/** Read stored key and validate it. Returns null if no key stored. */
function loadLicense(userDataPath) {
  try {
    const file = licensePath(userDataPath);
    if (!fs.existsSync(file)) return null;
    const key = fs.readFileSync(file, 'utf8').trim();
    const result = validateKey(key);
    return { ...result, key };
  } catch {
    return null;
  }
}

/** Save a valid key to disk. Throws if key is invalid. */
function saveLicense(userDataPath, key) {
  const result = validateKey(key);
  if (!result.valid) throw new Error(result.error || 'Invalid license key.');
  fs.writeFileSync(licensePath(userDataPath), key.trim(), 'utf8');
  return result;
}

/** Delete the stored license. */
function clearLicense(userDataPath) {
  const file = licensePath(userDataPath);
  if (fs.existsSync(file)) fs.unlinkSync(file);
}

// ─── Trial management ─────────────────────────────────────────────────────────

function getTrialStatus(userDataPath) {
  const file = trialPath(userDataPath);

  let startDate;
  if (fs.existsSync(file)) {
    startDate = new Date(fs.readFileSync(file, 'utf8').trim());
  } else {
    // First run — record trial start
    startDate = new Date();
    fs.writeFileSync(file, startDate.toISOString(), 'utf8');
  }

  const daysUsed = Math.floor((Date.now() - startDate.getTime()) / 86400000);
  const daysLeft = Math.max(0, TRIAL_DAYS - daysUsed);

  return {
    active:       daysLeft > 0,
    daysLeft,
    daysUsed,
    startDate:    startDate.toISOString().slice(0, 10),
    expiryDate:   new Date(startDate.getTime() + TRIAL_DAYS * 86400000).toISOString().slice(0, 10),
  };
}

// ─── Full status (used by IPC) ────────────────────────────────────────────────

/**
 * Returns the effective license status for the app.
 * Priority: valid license > trial > expired.
 */
function getStatus(userDataPath) {
  const license = loadLicense(userDataPath);
  const trial   = getTrialStatus(userDataPath);

  if (license && license.valid) {
    return { mode: 'licensed', license, trial };
  }

  if (trial.active) {
    return { mode: 'trial', license: license ?? null, trial };
  }

  return { mode: 'expired', license: license ?? null, trial };
}

module.exports = { buildKey, validateKey, loadLicense, saveLicense, clearLicense, getTrialStatus, getStatus };
