'use strict';

// Single home for barcode rules: format, GS1 check digits, the PBC- internal
// sequence, the EXTERNAL_BARCODE gate and uniqueness across products and variants.
// Controllers call these and never write barcode fields directly.

const mongoose = require('mongoose');
const Product  = require('../models/Product');
const Company  = require('../models/Company');
const { isFeatureEnabled } = require('./features.service');
const { BatchError }       = require('./stockBatch.service');

const INTERNAL_PREFIX  = 'PBC-';
const INTERNAL_PATTERN = /^PBC-\d{6,}$/;
const EXTERNAL_PATTERN = /^[A-Za-z0-9-]{4,64}$/;
const GTIN_LENGTHS     = new Set([8, 12, 13, 14]);
const MAX_RESERVE_TRIES = 20;

class BarcodeError extends Error {
  constructor(message, status = 422, extra = {}) {
    super(message);
    this.status = status;
    Object.assign(this, extra);
  }
}

// GS1 mod-10: weights 3 and 1 alternating from the right of the digits before the check digit.
function gtinCheckValid(digits) {
  const body = digits.slice(0, -1).split('').reverse().map(Number);
  const sum  = body.reduce((total, d, i) => total + d * (i % 2 === 0 ? 3 : 1), 0);
  return (10 - (sum % 10)) % 10 === Number(digits.slice(-1));
}

function normalizeBarcode(raw) {
  if (raw === undefined || raw === null) return null;
  // Barcodes never contain spaces. Typed codes often have them for readability, so drop all whitespace.
  const code = String(raw).replace(/\s+/g, '');
  return code === '' ? null : code;
}

// Validates a manufacturer barcode typed or scanned by a user. Returns the cleaned
// value, or null when the caller is clearing the barcode. Does not check the
// company's feature or uniqueness; prepareExternalBarcode does that.
function validateExternalFormat(raw) {
  const code = normalizeBarcode(raw);
  if (!code) return null;
  if (INTERNAL_PATTERN.test(code)) {
    throw new BarcodeError('PBC- codes are generated by PBC. Use Generate instead.');
  }
  if (!EXTERNAL_PATTERN.test(code)) {
    throw new BarcodeError('Barcode must be 4 to 64 letters, digits or hyphens.');
  }
  if (/^\d+$/.test(code) && GTIN_LENGTHS.has(code.length) && !gtinCheckValid(code)) {
    throw new BarcodeError('Barcode check digit is invalid. Check the number on the package.');
  }
  return code;
}

// True when `code` is already used by another product barcode or variant barcode in
// this company. Pass excludeProductId for a product write, or excludeVariantId for a
// variant write, so a record does not clash with its own current value.
async function barcodeInUse(companyId, code, { excludeProductId = null, excludeVariantId = null } = {}) {
  const productFilter = { company_id: companyId, barcode: code };
  if (excludeProductId) productFilter._id = { $ne: excludeProductId };
  if (await Product.exists(productFilter)) return true;

  const variantMatch = { barcode: code };
  if (excludeVariantId) variantMatch._id = { $ne: excludeVariantId };
  return !!(await Product.exists({ company_id: companyId, variants: { $elemMatch: variantMatch } }));
}

// Full check for a manufacturer barcode being written. Returns the cleaned code, or null
// when clearing.
async function prepareExternalBarcode(companyId, raw, scope = {}) {
  const code = validateExternalFormat(raw);
  if (!code) return null;
  if (!(await isFeatureEnabled(companyId, 'EXTERNAL_BARCODE'))) {
    throw new BarcodeError(
      'Manufacturer barcodes are not enabled for your business. Generate an internal barcode instead.',
      403,
      { code: 'FEATURE_DISABLED', feature: 'EXTERNAL_BARCODE' }
    );
  }
  if (await barcodeInUse(companyId, code, scope)) {
    throw new BarcodeError('Barcode already in use.', 409);
  }
  return code;
}

// Issues the next PBC- code for this company. The counter is incremented atomically,
// so two simultaneous requests cannot get the same number. A number already in use
// (for example one entered before this feature existed) is skipped.
async function nextInternalCode(companyId) {
  const company = await Company.findByIdAndUpdate(
    companyId,
    { $inc: { internal_barcode_seq: 1 } },
    { returnDocument: 'after', projection: { internal_barcode_seq: 1 } }
  ).lean();
  if (!company) throw new BarcodeError('Company not found.', 404);
  return `${INTERNAL_PREFIX}${String(company.internal_barcode_seq).padStart(6, '0')}`;
}

// Gives a product (or one of its variants) the next PBC- code. Only fills an empty
// barcode, so an existing manufacturer code is never replaced by this path.
async function assignInternalBarcode(companyId, { productId, variantId = null }) {
  const product = await Product.findOne({ _id: productId, company_id: companyId }, { barcode: 1, variants: 1 }).lean();
  if (!product) throw new BarcodeError('Product not found.', 404);

  let current = product.barcode;
  if (variantId) {
    const variant = product.variants?.find(v => String(v._id) === String(variantId));
    if (!variant) throw new BarcodeError('Variant not found.', 404);
    current = variant.barcode;
  }
  if (current) throw new BarcodeError('This already has a barcode. Clear it before generating an internal one.', 409);

  const scope = variantId
    ? { excludeVariantId: new mongoose.Types.ObjectId(variantId) }
    : { excludeProductId: product._id };

  for (let attempt = 0; attempt < MAX_RESERVE_TRIES; attempt++) {
    const code = await nextInternalCode(companyId);
    if (await barcodeInUse(companyId, code, scope)) continue;

    const emptyBarcode = { $in: [null, ''] };
    const now = new Date();
    try {
      const res = variantId
        ? await Product.updateOne(
            { _id: productId, company_id: companyId, variants: { $elemMatch: { _id: variantId, barcode: emptyBarcode } } },
            { $set: { 'variants.$.barcode': code, 'variants.$.barcode_type': 'internal', updated_at: now } }
          )
        : await Product.updateOne(
            { _id: productId, company_id: companyId, barcode: emptyBarcode },
            { $set: { barcode: code, barcode_type: 'internal', updated_at: now } }
          );
      if (res.matchedCount === 1) return code;
      throw new BarcodeError('This already has a barcode. Clear it before generating an internal one.', 409);
    } catch (err) {
      // Another request took this code between the check and the write. Try the next one.
      if (err.code === 11000) continue;
      throw err;
    }
  }
  throw new BarcodeError('Could not reserve a barcode. Try again.', 503);
}

// Maps barcode errors (and duplicate-key errors from the barcode indexes) to an HTTP
// response. Returns true when it sent one, so the caller can skip next(err).
function sendBarcodeError(res, err) {
  if (err instanceof BarcodeError || err instanceof BatchError) {
    const body = { success: false, message: err.message };
    if (err.code) { body.code = err.code; body.feature = err.feature; }
    res.status(err.status).json(body);
    return true;
  }
  if (err.code === 11000 && Object.keys(err.keyPattern || {}).some(k => k.includes('barcode'))) {
    res.status(409).json({ success: false, message: 'Barcode already in use.' });
    return true;
  }
  return false;
}

module.exports = {
  BarcodeError,
  INTERNAL_PREFIX,
  normalizeBarcode,
  validateExternalFormat,
  barcodeInUse,
  prepareExternalBarcode,
  assignInternalBarcode,
  sendBarcodeError,
};
